apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 10  # Minimum number of replicas
  maxReplicas: 20  # Maximum number of replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Scale based on 50% average CPU utilization across pods

# minReplicas: 10: Ensures that your deployment will always run a minimum of 10 pods.
# maxReplicas: 20: Allows scaling up to a maximum of 20 pods when needed.
# averageUtilization: 50: The HPA will scale the number of replicas dynamically to maintain an average CPU usage of 50% across all the pods. 
# If the CPU usage goes above 50%, the HPA will add more pods (up to 20), and if it goes below 50%, it will reduce the pods (no less than 10).
