apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Change as needed, but should be between 30000-32767
  selector:
    app.kubernetes.io/name: ingress-nginx
