apiVersion: v1
kind: ResourceQuota
metadata:
  name: nginx-resource-quota
  namespace: dev
spec:
  hard:
    pods: "5000"
    requests.cpu: "100"
    requests.memory: "500Gi"
    limits.cpu: "100"
    limits.memory: "500Gi"
